language: php,java
php:
  - "5.4"
sudo: false
install: true

jdk:
- oraclejdk8

branches:
  only:
    - master

before_script:
  - composer install --no-interaction
  - mkdir -p build/logs

script:
  - phpunit -v -c phpunit.xml --coverage-clover build/logs/clover.xml
  - ./runSonarQubeAnalysis.sh

cache:
  directories:
- '$HOME/.sonar/cache'
notifications:
  email: false

